apiVersion: apps/v1
kind: Deployment
metadata:
   name: cart
   labels:
      app: nodejs
      project: roboshop
      service: cart
      env: dev
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nodejs
         project: roboshop
         service: cart
         env: dev
   template:
      metadata:
         labels:
            app: nodejs
            project: roboshop
            service: cart
            env: dev
      spec:
         serviceAccountName: cart
         containers:
            - name: cart
              image: hemanthtadikonda/cart:1.0.0
              ports:
                 - containerPort: 8080
              envFrom:
                 -  configMapRef:
                       name: cart-config
              resources:
                 requests:
                    memory: "500Mi"
                    cpu: "250m"
                 limits:
                    memory: "500Mi"
                    cpu: "250m"
              livenessProbe:
                 httpGet:
                    path: /health
                    port: 8080
                 initialDelaySeconds: 10
                 periodSeconds: 5
              readinessProbe:
                 httpGet:
                    path: /health
                    port: 8080
                 initialDelaySeconds: 10
                 periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: cart
---
apiVersion: v1
kind: Service
metadata:
   name: cart
spec:
   selector:
      app: nodejs
      project: roboshop
      service: cart
      env: dev
   ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: cart-config
data:
   REDIS_HOST: 'redis'
   CATALOGUE_HOST: 'catalogue'
   CATALOGUE_PORT: '8080'