pipeline {
    agent any

    stages {
        stage('code compile') {
            steps {
                echo 'code compile'
            }
        }
        stage('code test') {
           steps {
               echooo 'code test'
           }
        }
        stage('code quality') {
            steps {
                echo 'code quality'
            }
        }
        stage('code security') {
           steps {
               echo 'code security'
           }
        }
    }
    post {
        always {
              echo 'post'
        }
    }
}






//@Library('roboshop') _

//env.component = "cart"
//env.codeType = "nodejs"
//cipipeline ()